### ISSUE TITLE
Need more google fonts 

### ISSUE THREAD

**Issue by constantine243** [YouCount/youcount.github.io#10]
can you add different google fonts like Rajdhani Roboto

**Comment by 20manas** [comment]
Why are there more fonts needed?

**Comment by constantine243** [comment]
to customize it for the live stream, currently the font used is of very thin style, it'll be great if you can add Rajdhani font as well, just a drop down list selection of font will be great.

**Comment by constantine243** [comment]
you there?

**Comment by 20manas** [comment]
Sorry for not replying earlier. This appears to be a very specific problem. How are you streaming? More importantly, where do you open the YouCount website?

**Comment by constantine243** [comment]
actually when i make the numbers small then the number completely disappear

**Comment by 20manas** [comment]
This is not supposed to happen. I cannot reproduce the bug. The font is resizing according to the size of the window, which is what is supposed to happen. Can you show me some code in which you're using the embed or perhaps some screenshots?
