### ISSUE TITLE
iFrame is a blank square

### ISSUE THREAD

**Issue by astrike30** [YouCount/youcount.github.io#2]
The embedded iFrame comes out as a blank square as shown in [this image here](https://imgur.com/9ra7weu) down below. Any idea what may be causing that? I have added the source for a test html file down below. Thanks for any help.

```
<!DOCTYPE html>
<html style="background-color: black">

<iframe src="https://youcount.github.io/e/#!/tseriesmusic" height="1000" width="2500" frameborder="0"></iframe>

</html>
```

**Comment by 20manas** [comment]
I think it's because you are running the page locally. It will probably start working correctly once you upload the page on a server and then load it from the URL of the page on the server.
