### ISSUE TITLE
Cant search anything

### ISSUE THREAD

**Issue by AryaDeepanshu** [YouCount/youcount.github.io#5]
Hi manas, I saw your project and liked it very much but when I downloaded it and started it in my browser it starts well but when we start typing it just shows loading in drop-down suggestion and when enter is pressed it shown no internet connection or refresh the page. Please help as soon as posssible

**Comment by 20manas** [comment]
Use the URL https://youcount.github.io to search for the channel name and find the code to use it as an embed in the menu.
